add : TypeORM ERD매핑
joog-lim/Bamboo-APIv3 pull request #3
Opened 2021-11-13 16:32 UTC by louis7308

TypeORM으로 ERD매핑시켜 Entities들 작성했습니다.

2021-11-13 17:51 UTC, sunrabbit123 requested changes
추가로 모델들을 넣어놓은 폴더의 이름은
폴더 자체가 여러 파일들을 모아놓은 복수형이기에 단수로 서술하는 것이 좋으며
몇 몇 쉘에서는 대소문자를 가리지않기도 하기때문에 전부 소문자로 서술하는 것이 좋습니다. (ex : cmd)

따라서 `model` 또는 `entity`라는 이름을 추천합니다.

2021-11-13 17:51 UTC, sunrabbit123 commented on src/Entities/Algorithem.ts
> +export class Algorithem {
mysql 내지 mariadb에서 사용되는 테이블 또는 컬럼들은 대소문자 구분이 없기때문에 `스네이크 표기법`을 이용합니다.
그에 비해 타입스크립트 내지 자바스크립트에서는 일반적으로 프로퍼티를 명명할 때 `파스칼 표기법`을 사용합니다.

`orm`으로 데이터베이스를 관리하는 해당 어플리케이션 특성 상
`파스칼 표기법`으로 프로퍼티 이름들을 명명하는게 좋지않을까 생각합니다.

2021-11-13 17:51 UTC, sunrabbit123 commented on src/Entities/Algorithem.ts
> +export class Algorithem_status {
Class의 이름의 경우 노션에 명시된대로 통일하는 것이 좋다고 생각합니다.

2021-11-13 17:51 UTC, sunrabbit123 commented on src/Entities/Algorithem.ts
> +export class question {
Class의 이름의 경우 노션에 명시된대로 파스칼케이스를 사용하는것이 좋다고 생각됩니다.

2021-11-13 17:51 UTC, sunrabbit123 commented on tsconfig.json
> +        "target": "ES5",
```suggestion
        "target": "es2020",
```
코딩을 하며 최근에 나온 문법들을 자주 사용할 것을 대비하여 2020버전을 추천합니다.

2021-11-13 17:51 UTC, sunrabbit123 commented on tsconfig.json
> +    "compilerOptions": {
```suggestion
    "include": ["./src/**/*", "./handler.ts"],
    "exclude": ["src/**/*.spec.ts", "src/**/*.test.ts", "node_modules"],
    "compilerOptions": {
        "typeRoots": ["./node_modules/@types"], // 타입들이 정의된 파일들의 위치
        "noImplicitAny": true, // any 타입으로 구현된 표현식 혹은 정의 에러처리
```

다음과 같이 컴파일할 파일들과 제외할 파일들을 선언하고
VSC의 도움을 받기 위하여, 타입루트 지정
그리고 `noImplicitAny`는 넣어주셨으면 합니다.

사실 제가 초기설정하면서 빼먹은게 큰거같네요 크흠..

```json
{
  "compilerOptions": {
    "module": "commonjs", // 모듈을 위한 코드 생성 설정(none, commonjs, amd, system)
    "target": "es2020", // 사용할 ECMAScript 버전 설정
    "outDir": "dist", // 결과 구조 보내는 디렉터리

    "noImplicitAny": true, // any 타입으로 구현된 표현식 혹은 정의 에러처리
    "strictPropertyInitialization": false, // 클래스 값 초기화에 엄격한 확인 여부
    "moduleResolution": "node", // 모듈 해석 방법
    "sourceMap": true, // .map 파일 생성 여부
    "experimentalDecorators": true, // ES7의 데코레이터에 대한실험적 지원 여부
    "emitDecoratorMetadata": true, // 데코레이터를 위한 타입 메타데이터를 내보내는 것에 대한 실험적 지원 여부
    "typeRoots": ["./node_modules/@types"]
  },
  "include": ["./src/**/*", "./handler.ts"],
  "exclude": ["src/**/*.spec.ts", "src/**/*.test.ts", "node_modules"]
}
```
타브랜치에서 선언한 tsconfig.json의 내용이니 참고해주시길 바랍니다 :D

2021-11-13 17:51 UTC, sunrabbit123 commented on src/Entities/User.ts
> +export class User {
mysql 내지 mariadb에서 사용되는 테이블 또는 컬럼들은 대소문자 구분이 없기때문에 스네이크 표기법을 이용합니다.
그에 비해 타입스크립트 내지 자바스크립트에서는 일반적으로 프로퍼티를 명명할 때 파스칼 표기법을 사용합니다.

orm으로 데이터베이스를 관리하는 해당 어플리케이션 특성 상
파스칼 표기법으로 프로퍼티 이름들을 명명하는게 좋지않을까 생각합니다.

2021-11-13 17:51 UTC, sunrabbit123 commented on package.json
> +    "@types/node": "^16.11.7",
```suggestion
    "@types/node": "^16.11.7",
```
해당 내용은 의존성보다는 개발 의존성에 위치해도 무관한 파일입니다.

타입의 경우 개발할때는 필요하지만, 빌드시에는 오히려 포함되면 용량만 잡아먹기때문입니다.

2021-11-13 17:51 UTC, sunrabbit123 commented on package.json
> +    "mysql2": "^2.3.3-rc.0",
따로 import 해서 사용하지않고 다른 패키지에 종속적으로 사용되는 모듈의 경우, 해당 패키지를 설치할 때 종속적으로 설치되니, package.json에 따로 언급해줄 필요는 없습니다.

꼭 필요한건지 여쭤보고싶습니다.

2021-11-13 17:51 UTC, sunrabbit123 commented on package.json
> +    "mysql2": "^2.3.3-rc.0",
추가로 따로 타입만 불러올거라면 개발 종속성에 타입만 추가하면 됩니다

2021-11-15 09:13 UTC, sunrabbit123 reviewed
자잘한 사항들 수정이 안된 것 같으니 체크해주세용

2021-11-15 09:13 UTC, sunrabbit123 commented on src/model/Algorithem.ts
> +export class Algorithem {
각 프로퍼티들을 카멜케이스로 적어주세용

ex : postId, postNumber, algorithemStatus

2021-11-15 09:13 UTC, sunrabbit123 commented on src/model/emojie.ts
> +export class Emojie {
```suggestion
export class Emoji {
```
오타가 있는 것 같네요. 전체적으로 `Emoji`로 수정해주세용

2021-11-15 09:25 UTC, louis7308 commented on src/model/emojie.ts
> +export class Emojie {
확인했습니다

2021-11-15 09:25 UTC, louis7308 commented on src/model/Algorithem.ts
> +export class Algorithem {
확인했습니다.

2021-11-16 01:17 UTC, sunrabbit123 approved these changes

2021-11-17 10:59 UTC, merged