Create Token
joog-lim/Bamboo-APIv3 pull request #9
Opened 2021-12-17 10:28 UTC by louis7308

1.  Oauth2 연동 작업 개발 완료
2.  대나무숲 전용 JWT 개발 완료
3.  JWT 생명유지 / 인증 개발 완료
4.  기존 유저가 다시 로그인 했을때 DB값을 추가하지 않고 UPDATE해서  값을 추가 개발 완료
5.  학교 이메일하고 지금 년도 비교 해서 학생인지 판단하는거 개발 완료

2021-12-17 12:56 UTC, sunrabbit123 requested changes
전체적으로 급하게 커밋을 한 느낌이 납니다. 주말 푹 쉬고, 필요가 없는 코드들은 이미 커밋 기록에 남아있으니 과감히 지우시고, 필요한 것들만 남김녀 좋을 것 같다는 생각이 듭니다.
예를 들어 OAuth 파트 중 클라이언트에서 처리하는 부분이 나와있는것들이 있네요.

2021-12-17 12:56 UTC, sunrabbit123 commented on package-lock.json
> +{
package.lock.json의 경우 개발자마다의 운영체제나 환경구성이 다를 수 있고, 패키지를 설치하면 기본적으로 생성되는 파일이니, 따로 푸쉬안해주셔도 됩니다.
.gitignore처리 부탁 드려요

2021-12-17 12:56 UTC, sunrabbit123 commented on serverless.yml
> +        # - DB_URL
여기 부분은 두번 반복되면서도 주석처리 되는지 여쭤봐도 될까요?

2021-12-17 12:56 UTC, sunrabbit123 commented on src/util/http.ts
> +export const decodeToken = ((token : any) => {
```suggestion
export const decodeToken = ((token : string) => {
```
토큰 값의 타입을 지정해주는 것이 추후, 함수를 가져와서 사용할 때 정적타이핑도구로써의 효용을 발휘하기 좋습니다.

2021-12-17 12:56 UTC, sunrabbit123 commented on src/util/http.ts
> +import { rejects } from "assert";
사용 안하는 모듈은 제거해주세요
```suggestion
```

2021-12-17 12:56 UTC, sunrabbit123 commented on src/util/http.ts
> +})
```ts
((token : any) => {
  try {
    return jwt.verify(token, process.env.JWT_SECRET);
  } catch (e) {
    return null;
  }
})
```
함수를 다음과 같이 괄호로 굳이 감싸줄 이유는 없다고 생각됩니다.

ex : 
```ts
export const decodeToken = (token: any) => {
  try {
    return jwt.verify(token, process.env.JWT_SECRET);
  } catch (e) {
    return null;
  }
};
```

2021-12-17 12:56 UTC, sunrabbit123 commented on src/util/http.ts
> +    return null;
```suggestion
    console.error(e);
    return null;
```
에러가 발생했을 시, 에러를 로그에 남겨야, 추후 서비스 운영시에 에러가 났을때 대응하기 수월해집니다.

2021-12-17 12:56 UTC, sunrabbit123 commented on src/util/http.ts
> +export const decodeToken = ((token : any) => {
```suggestion
export const decodeToken = ((token : any)  : null | JwtPayload | string => {
```
리턴 타입을 명시하는 것이, 타입스크립트 빌드시에 타입추론하기가 더욱 더 용이해집니다.

2021-12-17 12:56 UTC, sunrabbit123 commented on src/middleware/auth.ts
> +      const id = await repo.find({
테스트 당시에 사용하신 코드가 남아있는 것 같습니다.
이런 내용들은 추후 취약점이 되서 돌아올 가능성과 함께, 사이드이펙트를 불러올 수 있기때문에
테스트 당시의 코드들은 지우는 것을 지향해야한다고 생각합니다.

또한 삼항연산자의 사용을 얘기하기는 하였지만, 과도한 삼항연산자는 가독성을 해칩니다.
여러가지 조건들이 겹쳤기때문에, 이를 오브젝트와 여러 불린연산자들을 사용하여 추상화하는것을 추천드립니다.

2021-12-17 12:56 UTC, sunrabbit123 commented on src/router/auth/index.ts
> +          isAdmin: false
여기서 직접 모델 생성시의 기본값을 false로 설정하기보다는, Entity 폴더의 User.ts의 파일에서 isAdmin에 default : flase를 드리는 것을 추천드립니다.

2021-12-17 12:56 UTC, sunrabbit123 commented on src/router/auth/index.ts
> +          subId: decode.sub,
sub의 값은 유저에 따라서 고유하기때문에, 굳이 재 업데이트를 할 필요는 없다고 생각됩니다.

2021-12-17 12:56 UTC, sunrabbit123 commented on src/router/auth/index.ts
> +    const isStudent = nowYear % year == 0 ? true : (nowYear % year == 1 ? true : nowYear % year == 2 ? true : false)
복잡한 조건식은 함수로 만들어서 넣는 것이 가독성에 더욱 더 도움이 됩니다.

2021-12-21 08:12 UTC, louis7308 commented on serverless.yml
> +        # - DB_URL
저기 부분 example.env 에 값을 추가하지 못해가지고 오류나서 주석처리 해놓은거에요

2021-12-21 08:13 UTC, louis7308 commented on src/util/http.ts
> +export const decodeToken = ((token : any) => {
개발후 타입 어떻게 오는지 보고 바꿀려고 했는데 까먹고 있었네요 수정해놓겠습니다

2021-12-21 08:13 UTC, louis7308 commented on src/util/http.ts
> +import { rejects } from "assert";
저걸 추가한적이 없는데 아마 자동으로 갑자기 추가되는 현상때문에 생긴것 같습니다. ( 삭제 완료 )

2021-12-21 08:18 UTC, louis7308 commented on src/util/http.ts
> +})
넵

2021-12-21 08:25 UTC, louis7308 commented on src/router/auth/index.ts
> +          subId: decode.sub,
넵

2021-12-21 08:34 UTC, louis7308 commented on src/util/http.ts
> +export const decodeToken = ((token : any) => {
JwtPayLoad는 제가 따로 DTO 작성해서 만들어야 되는건가요 아니면 JWT 에서 지원해주는 타입인건가요?

2021-12-21 08:35 UTC, sunrabbit123 commented on src/util/http.ts
> +export const decodeToken = ((token : any) => {
JWT에서 기본적으로 지원하는 타입이에용~

2021-12-21 11:48 UTC, sunrabbit123 commented on serverless.yml
> +        # - DB_URL
코드 주석처리의 경우, 형상관리시스템인 git으로 관리되기때문에 푸쉬할 때 과감히 삭제해주시는게 좋을 것 같아요

2021-12-22 03:20 UTC, sunrabbit123 approved these changes
리팩토링은 서비스 개발 완료 후에 추가로 진행하는 것이 좋을 것 같네요
몇가지 점만 수정하고 머지하면 될 것 같아요

2021-12-22 03:20 UTC, sunrabbit123 commented on src/middleware/auth.ts
> +            errorCode: ERROR_CODE.JL001,
에러코드 `JL001`은 옳지않은 Origin일때 나타나는 에러입니다
새로 에러 코드를 선언해서 작성해주시길 바랍니다.

2021-12-22 03:20 UTC, sunrabbit123 commented on src/middleware/auth.ts
> +      const id = await repo.find({
유저의 id 조회는 필요할때만 조회해도 된다고 생각합니다.
if문 안쪽으로 넣는건 어떨까요?

2021-12-22 03:20 UTC, sunrabbit123 commented on src/router/auth/index.ts
> +        errorCode: ERROR_CODE.JL004,
JL004는 예상치못한 에러를 의미합니다.
새로 에러를 선언해서 작업해주시길 바랍니다.
참고 util/http.ts

2021-12-22 03:20 UTC, sunrabbit123 commented on src/util/http.ts
> +export const decodeToken = (token : string) : null | string | JwtPayload => {
http.ts보다는 token.ts가 어울릴 것 같아요

2021-12-22 11:36 UTC, merged